theme: jekyll-theme-chirpy
lang: en

# Change to your timezone
timezone: Asia/Kolkata

# jekyll-seo-tag settings
# ↓ --------------------------

title: Swagatika

tagline: Digital Alchemist - Turning Logic into Reality

description: >-
  Unveiling the essence of literature, code, and life through insightful book summaries, coding escapades, and occasional personal musings, curated by Swagatika.

# Fill in the protocol & hostname for your site.
# e.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://swagatika.me"

github:
  username: Swag3009

twitter:
  username: Swag3009

social:
  # Change to your full name.
  name: Swagatika Mohapatra
  email: mswagatika3009@gmail.com
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/Swag3009
    - https://twitter.com/Swag3009
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: "CHVzkd_VZu6Kx3I17OiGwPhSToA7ZDXzj850D-_XJQ4"

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: "G-NQNW6KJTPQ"

goatcounter:
  id: # fill in your Goatcounter ID

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#   light - Use the light color scheme
#   dark - Use the dark color scheme
#
theme_mode: # [light | dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

cloudinary_url: "https://res.cloudinary.com/dduot1vgo/image/upload/"
# the avatar on sidebar, support local or CORS resources
avatar: "assets/img/profile/profilePic.jpg"

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: "assets/img/favicons/android-chrome-384x384.png" # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  provider: giscus # The global switch for posts comments, e.g., 'disqus'. Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: Swag3009/swag3009.github.io # <gh-username>/<repo>
    repo_id: R_kgDOLcIFZA
    category: General
    category_id: DIC_kwDOLcIFZM4ChNXB
    mapping: og:title # optional, default to 'pathname'
    input_position: bottom # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: 1 # optional, default to the value of `1`

assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true # the option for PWA feature (installable)
  cache:
    enabled: true # the option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example" # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10

# The base URL of your site
baseurl: ""

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
